name: Self-hosted Runner Workflow

on:
  push:
    branches:
      - main  # Replace with your branch name
  #pull_request:
    #branches:
      #- main  # Replace with your branch name

  #workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: script
        run: |
          cp -r /* /home/site24x7/

      - name: script
        run: |
          echo "${{ github.workspace }}"
      # Add more steps as needed for your workflow
